yet another fix

diff --git a/HomeWork08/mymodule b/HomeWork08/mymodule
--- a/HomeWork08/mymodule
+++ b/HomeWork08/mymodule
@@ -8,15 +8,21 @@ function mvn_package
                         msg="change dir"
                         output=$(mvn package 2>&1 | python -c 'import json,sys; print json.dumps(sys.stdin.read())')
                         if [ $? -ne 0 ]; then
-                                printf '{"failed": true, "msg": "error mvn package", "output": %s}' "$output"
-                        exit 1
-            fi
+                                printf '{"failed": true, "msg": "error error command: mvn package", "output": %s}' "$output"
+                                exit 1
+                        fi
        else
                 changed="false"
                 msg="directory does not exists"
-                contents='""'
-       fi
+                contents='""
+                exit 1
+    fi
+
+
   }
+
+
+
 
 source $1
  if [ -z "$dest" ]; then
@@ -37,12 +43,12 @@ case $phase in
         mvn_package
         ;;
     *)
+
         printf '{"failed": true, "msg": "invalid phase: %s"}' "$phase"
-         exit 1
-                ;;
-        esac
+        exit 1
+        ;;
+esac
 
-        printf '{"changed": %s, "msg": "%s", "contents": %s}' "$changed" "$msg" "$contents"
+printf '{"changed": %s, "msg": "%s", "contents": %s}' "$changed" "$msg" "$output"
 
-        exit 0
-
+exit 0
